package ui.enums;

public enum ColorType {
    TRANSPARENT,
    BACKGROUND,
    DEFAULT_BORDER,
    DEFAULT_HIGHLIGHTED_BORDER,
    HIGHLIGHTED_SKIP_TURN_BORDER,
    CELL_IN_WORD,
    CHANGED_CELL,
    CANCEL_ACTION_BUTTON,
    SUBMIT_WORD_BUTTON,
    SKIP_TURN_BUTTON,
    ACTIVE_KEYBOARD_BUTTON,
    TABLE_HEADER,
    ACTIVE_PLAYER
}
