package ui.enums;

public enum ColorType {
    TRANSPARENT,
    DEFAULT_BORDER,
    HIGHLIGHTED_BORDER,
    HIGHLIGHTED_SKIP_TURN_BORDER,
    CELL_IN_WORD,
    CHANGED_CELL,
    CANCEL_ACTION_BUTTON,
    SUBMIT_WORD_BUTTON,
    SKIP_TURN_BUTTON,
    ACTIVE_ALPHABET_BUTTON,
    TABLE_HEADER,
    ACTIVE_PLAYER,
    TEXT_COLOR
}
