package ui;

public enum ColorType {
    TRANSPARENT,
    BACKGROUND,
    DEFAULT_BORDER,
    HOVERED_BORDER,
    CELL_IN_WORD,
    CHANGED_CELL,
    INACTIVE_CELL,
    CANCEL_ACTION_BUTTON,
    SUBMIT_WORD_BUTTON,
    SKIP_TURN_BUTTON,
    ACTIVE_KEYBOARD_BUTTON,
    INACTIVE_KEYBOARD_BUTTON
}
